### PR TITLE
Dont stop daemon when not running

### LINKED ISSUE #21: Use systemd for Duniter daemon
Confusing installation state when stopping upgrade script
When the upgrade script is manually stopped in the middle, debian package is removed but from YunoHost point of view it's still installed.
Then, `sudo duniter stop` command fail because `duniter` command no more exist, then because of `set -e`, the script fail.
Then, you stay stucked in a middle of an installed/not installed state

### PR DESCRIPTION
**Pull request by M5oul**
Fix #21 

https://github.com/duniter/duniter/pull/922 need to be released as stable on a debian package.

### CODE REVIEW

**Comment by M5oul** [comment]
It have been released on v.1.2.1 of duniter.

**Comment by c-geek** [comment]
I'm not sure duniter@1.2.1 is doing what you expect:

    duniter status
    Duniter is not running.

**Comment by c-geek** [comment]
Or

    duniter status
    Duniter is running using PID 7999.

**Comment by M5oul** [comment]
The [status of previous command is retrieved](https://github.com/YunoHost-Apps/duniter_ynh/blob/2d4040a9cf2a9fd2d0dc0bc7cf1b429ea1cae05a/scripts/functions.sh#L51-L52) which were implemented with on https://github.com/duniter/duniter/pull/922.

**Comment by c-geek** [comment]
Yes sorry, I was confusing `stdout` and `$?` values.

**Pull request merged**
