### PR TITLE
Switch to latest duniter release + ynh_port_find helper

### PR DESCRIPTION
**Pull request by nemsia**
Unable to install duniter on 2.6.2 yunohost test server without this helper 
and the v1.2.3 doesn't work at this time.

### CODE REVIEW

**Comment by M5oul** [comment]
Thanks for the bug report on YunoHost 2.6.2.
I fixed it with https://github.com/YunoHost/yunohost/pull/310.
I think we could keep this commit https://github.com/YunoHost-Apps/duniter_ynh/pull/48/commits/2ef0c293b30b8876e85b700c4bbf18c6c8ad6af4.

**Comment by nemsia** [comment]
This ok or i create new PR, (big noob inside...)

**Comment by M5oul** [comment]
You rebase to drop commits and keep the good one.
Or, if rebase it's too hard for you, you could create a new PR.

**Comment by nemsia** [comment]
New PR, sorry.

**Comment by M5oul** [comment]
Moved to https://github.com/YunoHost-Apps/duniter_ynh/pull/49.

**Pull request closed without merging**
