### PR TITLE
[fix] Activate BMA

### PR DESCRIPTION
**Pull request by M5oul**
It seems this is no longer activated by default

### CODE REVIEW

**Review by Thatoo — APPROVED** [review]
seems good to me

**Comment by lapineige** [comment]
What is BMA ?

**Comment by M5oul** [comment]
BMA has been disabled for Duniter v1.6.0:
- https://git.duniter.org/nodes/typescript/duniter/-/issues/1084
- in the commit duniter:`91f8d5d07af156e0d12288cca42fb684c0aef50d`

**Comment by M5oul** [comment]
BMA, is the client API.

**Pull request merged**
